### PR TITLE
close intro message support with localstorage

### PR DESCRIPTION
**Pull request by abel-baker**
Added "x" button function to hide (display: none) intro message; message only displays (display: initial) if the item "intro-message-seen" is not found in localStorage.

### CODE REVIEW

**Review by thevcr — APPROVED** [review]
🚢

**Comment by abel-baker** [comment]
Will review the conflicts and make changed necessary tomorrow morning.

**Comment by abel-baker** [comment]
Ready for another review 👍

**Comment by thevcr** [comment]
🚀

**Review by thevcr — APPROVED** [review]

**Comment by abel-baker** [comment]
Conflict resolved with form validation messages.

**Pull request merged**
